---
all:
  hosts:
    ansible-test:
      ansible_host: 192.168.122.166  # IP deiner VM
      ansible_user: ap14
      #ansible_become_pass: "{{ vault_sudo_password }}"  # Wird später mit Vault verschlüsselt
